algoritmo "Soma número"
// Função :Faça um algoritmo que receba dois números e exiba o resultado da soma
// Autor :Leandro Jesus
// Data : 19/4/2019

var
   num1, num2, soma:inteiro

inicio
   escreva("Digite o primeiro número: ")
   leia(num1)
   escreva("Digite o segundo número: ")
   leia(num2)
   soma <- num1+num2
   escreval("")
   escreva("O resultado da soma dos dois números é: ", soma)

fimalgoritmo
